### ISSUE TITLE
mysql协议格式似乎不全

### ISSUE THREAD

**Issue by Fuchange** [Orlion/hersql#3]
https://github.com/Orlion/hersql/blob/302ece385474e2e856fabe072dac845c4e6b84f7/sidecar/conn.go#L171

在`append(data, c.salt[8:]...)`和`append(data, []byte(mysql.MysqlNativePassword)...)`之间是不是应该有个`data = append(data, 0)`？

ubuntu 22.04上看抓包信息发现格式不对，补上 “00”后似乎正常了

![抓包信息解析为mysql协议后的异常](https://github.com/Orlion/hersql/assets/31716848/02fb9afd-2da9-463b-b7f2-4bedc6a3b4c8)

**Comment by Orlion** [comment]
感谢反馈已修复
